"""canonical itr360 tables

Revision ID: 06744b89bb08
Revises: 
Create Date: 2026-08-18 18:08:14.257721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06744b89bb08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # citext is used by person.primary_email and
    # identity_unresolved_queue.sender_email — not something
    # autogenerate can detect, added by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_table('decision_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index('ix_itr360_decision_audit_category_created_at', 'decision_audit', ['category', sa.literal_column('created_at DESC')], unique=False, schema='itr360')
    # append-only — not expressible in SQLAlchemy metadata, added by hand.
    op.execute("REVOKE UPDATE, DELETE ON itr360.decision_audit FROM PUBLIC")
    op.create_table('org',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_org_tenant_id'), 'org', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('problem_taxonomy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('problem_class', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example_phrases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('default_priority', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'problem_class'),
    schema='itr360'
    )
    op.create_table('recommendation_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('proposed_action_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('edit_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_token', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_recommendation_decision_tenant_id'), 'recommendation_decision', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('person',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('primary_email', postgresql.CITEXT(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['itr360.org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_person_tenant_id'), 'person', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('write_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('execution_ref', sa.Text(), nullable=True),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['itr360.recommendation_decision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_write_execution_tenant_id'), 'write_execution', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('case_',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.Text(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('intent_class', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('related_case_ids', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['itr360.org.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['itr360.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'case_number'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_case__tenant_id'), 'case_', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('identity_unresolved_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('src_message_id', sa.UUID(), nullable=False),
    sa.Column('sender_email', postgresql.CITEXT(), nullable=False),
    sa.Column('sender_display', sa.Text(), nullable=True),
    sa.Column('best_guess_person_id', sa.UUID(), nullable=True),
    sa.Column('best_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['best_guess_person_id'], ['itr360.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_identity_unresolved_queue_tenant_id'), 'identity_unresolved_queue', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_redacted', sa.Text(), nullable=False),
    sa.Column('pii_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pii_status', sa.Text(), nullable=False),
    sa.Column('src_message_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['itr360.case_.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['itr360.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_message_tenant_id'), 'message', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('triage_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('intent_class', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('sub_category', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('urgency_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('band', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('tier_used', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['itr360.case_.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_triage_result_tenant_id'), 'triage_result', ['tenant_id'], unique=False, schema='itr360')
    op.create_table('proposed_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('triage_result_id', sa.UUID(), nullable=True),
    sa.Column('resolution_path', sa.Text(), nullable=True),
    sa.Column('recommended_action_text', sa.Text(), nullable=False),
    sa.Column('draft_sentences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('recommended_owner', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_ref', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_token', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['itr360.case_.id'], ),
    sa.ForeignKeyConstraint(['triage_result_id'], ['itr360.triage_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_proposed_action_tenant_id'), 'proposed_action', ['tenant_id'], unique=False, schema='itr360')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itr360_proposed_action_tenant_id'), table_name='proposed_action', schema='itr360')
    op.drop_table('proposed_action', schema='itr360')
    op.drop_index(op.f('ix_itr360_triage_result_tenant_id'), table_name='triage_result', schema='itr360')
    op.drop_table('triage_result', schema='itr360')
    op.drop_index(op.f('ix_itr360_message_tenant_id'), table_name='message', schema='itr360')
    op.drop_table('message', schema='itr360')
    op.drop_index(op.f('ix_itr360_identity_unresolved_queue_tenant_id'), table_name='identity_unresolved_queue', schema='itr360')
    op.drop_table('identity_unresolved_queue', schema='itr360')
    op.drop_index(op.f('ix_itr360_case__tenant_id'), table_name='case_', schema='itr360')
    op.drop_table('case_', schema='itr360')
    op.drop_index(op.f('ix_itr360_write_execution_tenant_id'), table_name='write_execution', schema='itr360')
    op.drop_table('write_execution', schema='itr360')
    op.drop_index(op.f('ix_itr360_person_tenant_id'), table_name='person', schema='itr360')
    op.drop_table('person', schema='itr360')
    op.drop_index(op.f('ix_itr360_recommendation_decision_tenant_id'), table_name='recommendation_decision', schema='itr360')
    op.drop_table('recommendation_decision', schema='itr360')
    op.drop_table('problem_taxonomy', schema='itr360')
    op.drop_index(op.f('ix_itr360_org_tenant_id'), table_name='org', schema='itr360')
    op.drop_table('org', schema='itr360')
    op.drop_index('ix_itr360_decision_audit_category_created_at', table_name='decision_audit', schema='itr360')
    op.drop_table('decision_audit', schema='itr360')
    op.drop_table('case_event', schema='itr360')
    # ### end Alembic commands ###
