"""message src_message_id uuid to text

Revision ID: 29df1929cdaf
Revises: ca42ac33aee8
Create Date: 2026-08-18 20:49:16.102855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29df1929cdaf'
down_revision: Union[str, None] = 'ca42ac33aee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'src_message_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='itr360')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'src_message_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='itr360')
    # ### end Alembic commands ###
