"""raw_ingest quarantine table

Revision ID: 5835576deac8
Revises: c4a9df947985
Create Date: 2026-08-18 22:31:48.703710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5835576deac8'
down_revision: Union[str, None] = 'c4a9df947985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantine',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_path', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_ingest'
    )
    op.create_index(op.f('ix_raw_ingest_quarantine_tenant_id'), 'quarantine', ['tenant_id'], unique=False, schema='raw_ingest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_ingest_quarantine_tenant_id'), table_name='quarantine', schema='raw_ingest')
    op.drop_table('quarantine', schema='raw_ingest')
    # ### end Alembic commands ###
