"""identity_unresolved_queue src_message_id uuid to text

Revision ID: 925ed25e0fa9
Revises: 29df1929cdaf
Create Date: 2026-08-18 21:01:42.796328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925ed25e0fa9'
down_revision: Union[str, None] = '29df1929cdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('identity_unresolved_queue', 'src_message_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False,
               schema='itr360')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('identity_unresolved_queue', 'src_message_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='itr360')
    # ### end Alembic commands ###
