"""message thread_id column

Revision ID: c4a9df947985
Revises: 925ed25e0fa9
Create Date: 2026-08-18 22:16:19.568121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a9df947985'
down_revision: Union[str, None] = '925ed25e0fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thread_id', sa.Text(), nullable=True), schema='itr360')
    op.create_index(op.f('ix_itr360_message_thread_id'), 'message', ['thread_id'], unique=False, schema='itr360')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itr360_message_thread_id'), table_name='message', schema='itr360')
    op.drop_column('message', 'thread_id', schema='itr360')
    # ### end Alembic commands ###
