"""person email alias table

Revision ID: ca42ac33aee8
Revises: 06744b89bb08
Create Date: 2026-08-18 19:44:39.632952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca42ac33aee8'
down_revision: Union[str, None] = '06744b89bb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_email_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_kind', sa.Text(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('connector_run_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['itr360.person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email'),
    schema='itr360'
    )
    op.create_index(op.f('ix_itr360_person_email_alias_tenant_id'), 'person_email_alias', ['tenant_id'], unique=False, schema='itr360')
    op.create_index('ix_itr360_person_email_alias_tenant_id_email', 'person_email_alias', ['tenant_id', 'email'], unique=False, schema='itr360')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itr360_person_email_alias_tenant_id_email', table_name='person_email_alias', schema='itr360')
    op.drop_index(op.f('ix_itr360_person_email_alias_tenant_id'), table_name='person_email_alias', schema='itr360')
    op.drop_table('person_email_alias', schema='itr360')
    # ### end Alembic commands ###
