-- 009 — itr360.kb_article
--
-- Knowledge Base solution articles, one per (category, problem_class,
-- title). Generated by scripts/generate_kb_articles.py and indexed into
-- the SAME Qdrant collection Task 17 uses (see scout/context/kb_index.py),
-- so retrieve()/compile() surface them next to email evidence for triage
-- and drafting.
--
-- Wrapped in Alembic as scout/migrations/versions/7f2a1c9d4e3b_kb_article_table.py.
-- This file is the readable reference DDL; the migration is what runs.
--
-- Provenance columns (tenant_id, source_system, external_id, is_synthetic,
-- connector_run_id, observed_at, valid_from) follow the Task 4 mixin
-- exactly. source_system is 'kb_article' for every row — that is also the
-- value carried in the Qdrant payload so compile.py can branch on it.

CREATE TABLE itr360.kb_article (
  id uuid PRIMARY KEY,
  category text NOT NULL,
  problem_class text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  source text NOT NULL DEFAULT 'llm_generated',
  model_name text,

  tenant_id uuid NOT NULL,
  source_system text NOT NULL,
  external_id text,
  is_synthetic boolean NOT NULL DEFAULT false,
  connector_run_id uuid NOT NULL,
  observed_at timestamptz NOT NULL,
  valid_from timestamptz NOT NULL,

  FOREIGN KEY (category, problem_class)
    REFERENCES itr360.problem_taxonomy (category, problem_class),
  UNIQUE (tenant_id, category, problem_class, title)
);

CREATE INDEX ix_itr360_kb_article_tenant_id ON itr360.kb_article (tenant_id);
CREATE INDEX ix_itr360_kb_article_class ON itr360.kb_article (category, problem_class);
